name: Deploy to Amazon ECS
run-name: Deploy to ${{ github.event.inputs.env }} ${{ github.event.inputs.facility }} by @${{ github.actor }}
on:
  workflow_dispatch:
    branches:
      - 'main'
    inputs:
      env:
        type: choice
        description: "Which Environment"
        required: true
        options:
          - cert
          - prod
      facility:
        description: "Facility Id Prefix"
        required: true
        type: string
      use_common_secrets:
        description: "Use Common Secrets Key?"
        required: true
        type: choice
        options:
          - yes
          - no

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Validate
        if: ${{ !fromJson(vars.BACKEND_CONFIG)[github.event.inputs.env]['facilities'][github.event.inputs.facility] }}
        run: |
          echo "Missing Facility Id in Config"
          exit 1
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Task Definition (Conditional)
        if: ${{ github.event.inputs.use_common_secrets == 'yes' }}
        run: |
          echo "Prepare Task Definition (Conditional) step"
          
          with:
            input: ./.aws/demo.json.tmpl
         
