name: Hello world

on:
  [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Set AWS Region
        run: echo "AWS_REGION=${{ secrets.MY_AWS_REGION }}" >> $GITHUB_ENV

      - name: Display AWS Region
        run: echo "AWS Region is ${{ env.AWS_REGION }}"
