name: Set AWS Region

on:
  push:
   

env:
  AWS_REGION: us-east-1 # Set this to your preferred AWS region, e.g. us-west-1

jobs:
  set-region:
    name: Set Region
    runs-on: ubuntu-latest

    steps:
      - name: Set AWS Region
        run: echo "::set-env name=AWS_REGION::${{ env.AWS_REGION }}"
