name: If-Else Condition Example

on:
  push:
    branches:
      - main

jobs:
  if_else_example:
    runs-on: ubuntu-latest

    steps:
      - name: Check Condition
        run: echo "::set-output name=condition::${{ github.event.inputs.condition }}"
        id: check_condition

      - name: Execute if condition is true
        if: steps.check_condition.outputs.condition == 'true'
        run: echo "Condition is true, do something..."

      - name: Execute if condition is false
        if: steps.check_condition.outputs.condition == 'false'
        run: echo "Condition is false, do something else..."
